setting:
  name: "test_hilti"
  output_root: "./experiments"
  pc_path: "./data/HILTI/cons2/ply" #rpg, lab, base1, base4, camp2, cons2
  deskew: True
process:
  min_range_m: 1.0
  max_range_m: 60.0
  min_z_m: -10.0
  vox_down_m: 0.06
  adaptive_range_on: True
sampler:
  surface_sample_range_m: 0.25
  surface_sample_n: 4
  free_sample_begin_ratio: 0.5
  free_sample_end_dist_m: 1.0
  free_front_sample_n: 2 
neuralpoints:
  voxel_size_m: 0.3
  search_alpha: 0.8
loss:
  sigma_sigmoid_m: 0.08
  loss_weight_on: True
  dist_weight_scale: 0.8
  ekional_loss_on: True
  weight_e: 0.5
continual:
  batch_size_new_sample: 1000
  pool_capacity: 2e7
tracker:
  source_vox_down_m: 0.4
  iter_n: 100
pgo:
  map_context: True
  pgo_freq_frame: 30
optimizer: # mapper
  iters: 15  # iterations per frame
  batch_size: 16384
  adaptive_iters: True
eval:
  mesh_freq_frame: 50 # reconstruct the mesh every x frames
  mesh_min_nn: 18