setting:
  name: "sanity_test_sem"
  output_root: "./experiments"
  pc_path: "./data/kitti_example/sequences/00/velodyne"
  label_path: "./data/kitti_example/sequences/00/labels"
  semantic_on: True
process:
  max_range_m: 60.0
tracker:
  iter_n: 20
eval:
  sensor_cad_path: ./cad/kitti_car.ply